// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRjTRHzHI3e7A0a1Ak9yeXG_gTW4xytU',
    appId: '1:32707752970:web:b2caf328e6eae12798dbf3',
    messagingSenderId: '32707752970',
    projectId: 'decibel-1774203293120',
    authDomain: 'decibel-1774203293120.firebaseapp.com',
    storageBucket: 'decibel-1774203293120.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0zAI5FPcqhAV_jcaiXr98PXkRfotlAvU',
    appId: '1:32707752970:android:704eba5538c8303598dbf3',
    messagingSenderId: '32707752970',
    projectId: 'decibel-1774203293120',
    storageBucket: 'decibel-1774203293120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3KisxuVqhsoe8ug43s8gtn-9cjUjZ0hw',
    appId: '1:32707752970:ios:ae3353f5c054024c98dbf3',
    messagingSenderId: '32707752970',
    projectId: 'decibel-1774203293120',
    storageBucket: 'decibel-1774203293120.firebasestorage.app',
    androidClientId:
        '32707752970-iogrei2270q4qni8eicn9r8osb1006mr.apps.googleusercontent.com',
    iosBundleId: 'com.decibel.decibel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3KisxuVqhsoe8ug43s8gtn-9cjUjZ0hw',
    appId: '1:32707752970:ios:ae3353f5c054024c98dbf3',
    messagingSenderId: '32707752970',
    projectId: 'decibel-1774203293120',
    storageBucket: 'decibel-1774203293120.firebasestorage.app',
    androidClientId:
        '32707752970-iogrei2270q4qni8eicn9r8osb1006mr.apps.googleusercontent.com',
    iosBundleId: 'com.decibel.decibel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZRjTRHzHI3e7A0a1Ak9yeXG_gTW4xytU',
    appId: '1:32707752970:web:18e560b51a2ced5f98dbf3',
    messagingSenderId: '32707752970',
    projectId: 'decibel-1774203293120',
    authDomain: 'decibel-1774203293120.firebaseapp.com',
    storageBucket: 'decibel-1774203293120.firebasestorage.app',
  );
}
