name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Run Code Generation 
        run: dart run build_runner build --delete-conflicting-outputs
        
    #   - name: Analyze Code (Linting)
    #     run: flutter analyze --fatal-warnings
        
      - name: Run Tests
        run: flutter test

  build-android:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: temurin
            java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml 
          cache: true
          pub-cache: true
            
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/debug-info

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: decibel-android-release
          path: build/app/outputs/flutter-apk/*-release.apk
          retention-days: 1
          
  build-windows:
    needs: lint-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml 
          cache: true
          pub-cache: true
          
      - run: flutter pub get
      
      - name: Build Windows Desktop App
        run: flutter build windows --release
                  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: decibel-windows-release
          path: build\windows\x64\runner\Release\
          retention-days: 1
